name: Compile Linux

on:
  push:
    branches:
    - master
    paths:
    - 'MCPPPP-windows.exe'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: install libc++
      run: sudo apt update && sudo apt install libc++abi1-12 -y && sudo apt install libc++1-12 -y && sudo apt install libc++-12-dev -y && sudo apt install clang -y
    - name: cli
      run: g++ Source.cpp -Ofast -std=c++20 -stdlib=libc++ -o bin/MCPPPP-linux
    - name: gui
      run: g++ -I./ -DGUI -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_THREAD_SAFE -D_REENTRANT Source.cpp lib/libfltk.a -lXrender -lXext -lXft -lfontconfig -lpthread -ldl -lm -lX11 -std=c++20 -stdlib=libc++ -o bin/MCPPPP-linux-gui
    - uses: EndBug/add-and-commit@v7
      with:
        add: '["bin/MCPPPP-linux", "bin/MCPPPP-linux-gui"]'
        message: 'add linux binary'
        push: true
